services:
  - type: web
    name: my-vite-app
    env: node
    buildCommand: npm install && npm run build
    startCommand: npm run serve
    envVars:
      - key: NODE_VERSION
        value: 18
    plan: free